# CMake generated Testfile for 
# Source directory: /home/qifei/pm_source/ye_db/pm_db
# Build directory: /home/qifei/pm_source/ye_db/pm_db/cmake-build
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(c_test "/home/qifei/pm_source/ye_db/pm_db/cmake-build/c_test")
set_tests_properties(c_test PROPERTIES  _BACKTRACE_TRIPLES "/home/qifei/pm_source/ye_db/pm_db/CMakeLists.txt;344;add_test;/home/qifei/pm_source/ye_db/pm_db/CMakeLists.txt;347;leveldb_test;/home/qifei/pm_source/ye_db/pm_db/CMakeLists.txt;0;")
add_test(fault_injection_test "/home/qifei/pm_source/ye_db/pm_db/cmake-build/fault_injection_test")
set_tests_properties(fault_injection_test PROPERTIES  _BACKTRACE_TRIPLES "/home/qifei/pm_source/ye_db/pm_db/CMakeLists.txt;344;add_test;/home/qifei/pm_source/ye_db/pm_db/CMakeLists.txt;348;leveldb_test;/home/qifei/pm_source/ye_db/pm_db/CMakeLists.txt;0;")
add_test(issue178_test "/home/qifei/pm_source/ye_db/pm_db/cmake-build/issue178_test")
set_tests_properties(issue178_test PROPERTIES  _BACKTRACE_TRIPLES "/home/qifei/pm_source/ye_db/pm_db/CMakeLists.txt;344;add_test;/home/qifei/pm_source/ye_db/pm_db/CMakeLists.txt;350;leveldb_test;/home/qifei/pm_source/ye_db/pm_db/CMakeLists.txt;0;")
add_test(issue200_test "/home/qifei/pm_source/ye_db/pm_db/cmake-build/issue200_test")
set_tests_properties(issue200_test PROPERTIES  _BACKTRACE_TRIPLES "/home/qifei/pm_source/ye_db/pm_db/CMakeLists.txt;344;add_test;/home/qifei/pm_source/ye_db/pm_db/CMakeLists.txt;351;leveldb_test;/home/qifei/pm_source/ye_db/pm_db/CMakeLists.txt;0;")
add_test(issue320_test "/home/qifei/pm_source/ye_db/pm_db/cmake-build/issue320_test")
set_tests_properties(issue320_test PROPERTIES  _BACKTRACE_TRIPLES "/home/qifei/pm_source/ye_db/pm_db/CMakeLists.txt;344;add_test;/home/qifei/pm_source/ye_db/pm_db/CMakeLists.txt;352;leveldb_test;/home/qifei/pm_source/ye_db/pm_db/CMakeLists.txt;0;")
add_test(env_test "/home/qifei/pm_source/ye_db/pm_db/cmake-build/env_test")
set_tests_properties(env_test PROPERTIES  _BACKTRACE_TRIPLES "/home/qifei/pm_source/ye_db/pm_db/CMakeLists.txt;344;add_test;/home/qifei/pm_source/ye_db/pm_db/CMakeLists.txt;354;leveldb_test;/home/qifei/pm_source/ye_db/pm_db/CMakeLists.txt;0;")
add_test(status_test "/home/qifei/pm_source/ye_db/pm_db/cmake-build/status_test")
set_tests_properties(status_test PROPERTIES  _BACKTRACE_TRIPLES "/home/qifei/pm_source/ye_db/pm_db/CMakeLists.txt;344;add_test;/home/qifei/pm_source/ye_db/pm_db/CMakeLists.txt;355;leveldb_test;/home/qifei/pm_source/ye_db/pm_db/CMakeLists.txt;0;")
add_test(no_destructor_test "/home/qifei/pm_source/ye_db/pm_db/cmake-build/no_destructor_test")
set_tests_properties(no_destructor_test PROPERTIES  _BACKTRACE_TRIPLES "/home/qifei/pm_source/ye_db/pm_db/CMakeLists.txt;344;add_test;/home/qifei/pm_source/ye_db/pm_db/CMakeLists.txt;356;leveldb_test;/home/qifei/pm_source/ye_db/pm_db/CMakeLists.txt;0;")
add_test(autocompact_test "/home/qifei/pm_source/ye_db/pm_db/cmake-build/autocompact_test")
set_tests_properties(autocompact_test PROPERTIES  _BACKTRACE_TRIPLES "/home/qifei/pm_source/ye_db/pm_db/CMakeLists.txt;344;add_test;/home/qifei/pm_source/ye_db/pm_db/CMakeLists.txt;359;leveldb_test;/home/qifei/pm_source/ye_db/pm_db/CMakeLists.txt;0;")
add_test(corruption_test "/home/qifei/pm_source/ye_db/pm_db/cmake-build/corruption_test")
set_tests_properties(corruption_test PROPERTIES  _BACKTRACE_TRIPLES "/home/qifei/pm_source/ye_db/pm_db/CMakeLists.txt;344;add_test;/home/qifei/pm_source/ye_db/pm_db/CMakeLists.txt;360;leveldb_test;/home/qifei/pm_source/ye_db/pm_db/CMakeLists.txt;0;")
add_test(db_test "/home/qifei/pm_source/ye_db/pm_db/cmake-build/db_test")
set_tests_properties(db_test PROPERTIES  _BACKTRACE_TRIPLES "/home/qifei/pm_source/ye_db/pm_db/CMakeLists.txt;344;add_test;/home/qifei/pm_source/ye_db/pm_db/CMakeLists.txt;361;leveldb_test;/home/qifei/pm_source/ye_db/pm_db/CMakeLists.txt;0;")
add_test(dbformat_test "/home/qifei/pm_source/ye_db/pm_db/cmake-build/dbformat_test")
set_tests_properties(dbformat_test PROPERTIES  _BACKTRACE_TRIPLES "/home/qifei/pm_source/ye_db/pm_db/CMakeLists.txt;344;add_test;/home/qifei/pm_source/ye_db/pm_db/CMakeLists.txt;362;leveldb_test;/home/qifei/pm_source/ye_db/pm_db/CMakeLists.txt;0;")
add_test(filename_test "/home/qifei/pm_source/ye_db/pm_db/cmake-build/filename_test")
set_tests_properties(filename_test PROPERTIES  _BACKTRACE_TRIPLES "/home/qifei/pm_source/ye_db/pm_db/CMakeLists.txt;344;add_test;/home/qifei/pm_source/ye_db/pm_db/CMakeLists.txt;363;leveldb_test;/home/qifei/pm_source/ye_db/pm_db/CMakeLists.txt;0;")
add_test(log_test "/home/qifei/pm_source/ye_db/pm_db/cmake-build/log_test")
set_tests_properties(log_test PROPERTIES  _BACKTRACE_TRIPLES "/home/qifei/pm_source/ye_db/pm_db/CMakeLists.txt;344;add_test;/home/qifei/pm_source/ye_db/pm_db/CMakeLists.txt;364;leveldb_test;/home/qifei/pm_source/ye_db/pm_db/CMakeLists.txt;0;")
add_test(recovery_test "/home/qifei/pm_source/ye_db/pm_db/cmake-build/recovery_test")
set_tests_properties(recovery_test PROPERTIES  _BACKTRACE_TRIPLES "/home/qifei/pm_source/ye_db/pm_db/CMakeLists.txt;344;add_test;/home/qifei/pm_source/ye_db/pm_db/CMakeLists.txt;365;leveldb_test;/home/qifei/pm_source/ye_db/pm_db/CMakeLists.txt;0;")
add_test(skiplist_test "/home/qifei/pm_source/ye_db/pm_db/cmake-build/skiplist_test")
set_tests_properties(skiplist_test PROPERTIES  _BACKTRACE_TRIPLES "/home/qifei/pm_source/ye_db/pm_db/CMakeLists.txt;344;add_test;/home/qifei/pm_source/ye_db/pm_db/CMakeLists.txt;366;leveldb_test;/home/qifei/pm_source/ye_db/pm_db/CMakeLists.txt;0;")
add_test(version_edit_test "/home/qifei/pm_source/ye_db/pm_db/cmake-build/version_edit_test")
set_tests_properties(version_edit_test PROPERTIES  _BACKTRACE_TRIPLES "/home/qifei/pm_source/ye_db/pm_db/CMakeLists.txt;344;add_test;/home/qifei/pm_source/ye_db/pm_db/CMakeLists.txt;367;leveldb_test;/home/qifei/pm_source/ye_db/pm_db/CMakeLists.txt;0;")
add_test(version_set_test "/home/qifei/pm_source/ye_db/pm_db/cmake-build/version_set_test")
set_tests_properties(version_set_test PROPERTIES  _BACKTRACE_TRIPLES "/home/qifei/pm_source/ye_db/pm_db/CMakeLists.txt;344;add_test;/home/qifei/pm_source/ye_db/pm_db/CMakeLists.txt;368;leveldb_test;/home/qifei/pm_source/ye_db/pm_db/CMakeLists.txt;0;")
add_test(write_batch_test "/home/qifei/pm_source/ye_db/pm_db/cmake-build/write_batch_test")
set_tests_properties(write_batch_test PROPERTIES  _BACKTRACE_TRIPLES "/home/qifei/pm_source/ye_db/pm_db/CMakeLists.txt;344;add_test;/home/qifei/pm_source/ye_db/pm_db/CMakeLists.txt;369;leveldb_test;/home/qifei/pm_source/ye_db/pm_db/CMakeLists.txt;0;")
add_test(large_value_test "/home/qifei/pm_source/ye_db/pm_db/cmake-build/large_value_test")
set_tests_properties(large_value_test PROPERTIES  _BACKTRACE_TRIPLES "/home/qifei/pm_source/ye_db/pm_db/CMakeLists.txt;344;add_test;/home/qifei/pm_source/ye_db/pm_db/CMakeLists.txt;370;leveldb_test;/home/qifei/pm_source/ye_db/pm_db/CMakeLists.txt;0;")
add_test(memenv_test "/home/qifei/pm_source/ye_db/pm_db/cmake-build/memenv_test")
set_tests_properties(memenv_test PROPERTIES  _BACKTRACE_TRIPLES "/home/qifei/pm_source/ye_db/pm_db/CMakeLists.txt;344;add_test;/home/qifei/pm_source/ye_db/pm_db/CMakeLists.txt;372;leveldb_test;/home/qifei/pm_source/ye_db/pm_db/CMakeLists.txt;0;")
add_test(filter_block_test "/home/qifei/pm_source/ye_db/pm_db/cmake-build/filter_block_test")
set_tests_properties(filter_block_test PROPERTIES  _BACKTRACE_TRIPLES "/home/qifei/pm_source/ye_db/pm_db/CMakeLists.txt;344;add_test;/home/qifei/pm_source/ye_db/pm_db/CMakeLists.txt;374;leveldb_test;/home/qifei/pm_source/ye_db/pm_db/CMakeLists.txt;0;")
add_test(table_test "/home/qifei/pm_source/ye_db/pm_db/cmake-build/table_test")
set_tests_properties(table_test PROPERTIES  _BACKTRACE_TRIPLES "/home/qifei/pm_source/ye_db/pm_db/CMakeLists.txt;344;add_test;/home/qifei/pm_source/ye_db/pm_db/CMakeLists.txt;375;leveldb_test;/home/qifei/pm_source/ye_db/pm_db/CMakeLists.txt;0;")
add_test(arena_test "/home/qifei/pm_source/ye_db/pm_db/cmake-build/arena_test")
set_tests_properties(arena_test PROPERTIES  _BACKTRACE_TRIPLES "/home/qifei/pm_source/ye_db/pm_db/CMakeLists.txt;344;add_test;/home/qifei/pm_source/ye_db/pm_db/CMakeLists.txt;377;leveldb_test;/home/qifei/pm_source/ye_db/pm_db/CMakeLists.txt;0;")
add_test(bloom_test "/home/qifei/pm_source/ye_db/pm_db/cmake-build/bloom_test")
set_tests_properties(bloom_test PROPERTIES  _BACKTRACE_TRIPLES "/home/qifei/pm_source/ye_db/pm_db/CMakeLists.txt;344;add_test;/home/qifei/pm_source/ye_db/pm_db/CMakeLists.txt;378;leveldb_test;/home/qifei/pm_source/ye_db/pm_db/CMakeLists.txt;0;")
add_test(cache_test "/home/qifei/pm_source/ye_db/pm_db/cmake-build/cache_test")
set_tests_properties(cache_test PROPERTIES  _BACKTRACE_TRIPLES "/home/qifei/pm_source/ye_db/pm_db/CMakeLists.txt;344;add_test;/home/qifei/pm_source/ye_db/pm_db/CMakeLists.txt;379;leveldb_test;/home/qifei/pm_source/ye_db/pm_db/CMakeLists.txt;0;")
add_test(coding_test "/home/qifei/pm_source/ye_db/pm_db/cmake-build/coding_test")
set_tests_properties(coding_test PROPERTIES  _BACKTRACE_TRIPLES "/home/qifei/pm_source/ye_db/pm_db/CMakeLists.txt;344;add_test;/home/qifei/pm_source/ye_db/pm_db/CMakeLists.txt;380;leveldb_test;/home/qifei/pm_source/ye_db/pm_db/CMakeLists.txt;0;")
add_test(crc32c_test "/home/qifei/pm_source/ye_db/pm_db/cmake-build/crc32c_test")
set_tests_properties(crc32c_test PROPERTIES  _BACKTRACE_TRIPLES "/home/qifei/pm_source/ye_db/pm_db/CMakeLists.txt;344;add_test;/home/qifei/pm_source/ye_db/pm_db/CMakeLists.txt;381;leveldb_test;/home/qifei/pm_source/ye_db/pm_db/CMakeLists.txt;0;")
add_test(hash_test "/home/qifei/pm_source/ye_db/pm_db/cmake-build/hash_test")
set_tests_properties(hash_test PROPERTIES  _BACKTRACE_TRIPLES "/home/qifei/pm_source/ye_db/pm_db/CMakeLists.txt;344;add_test;/home/qifei/pm_source/ye_db/pm_db/CMakeLists.txt;382;leveldb_test;/home/qifei/pm_source/ye_db/pm_db/CMakeLists.txt;0;")
add_test(logging_test "/home/qifei/pm_source/ye_db/pm_db/cmake-build/logging_test")
set_tests_properties(logging_test PROPERTIES  _BACKTRACE_TRIPLES "/home/qifei/pm_source/ye_db/pm_db/CMakeLists.txt;344;add_test;/home/qifei/pm_source/ye_db/pm_db/CMakeLists.txt;383;leveldb_test;/home/qifei/pm_source/ye_db/pm_db/CMakeLists.txt;0;")
add_test(value_test "/home/qifei/pm_source/ye_db/pm_db/cmake-build/value_test")
set_tests_properties(value_test PROPERTIES  _BACKTRACE_TRIPLES "/home/qifei/pm_source/ye_db/pm_db/CMakeLists.txt;344;add_test;/home/qifei/pm_source/ye_db/pm_db/CMakeLists.txt;385;leveldb_test;/home/qifei/pm_source/ye_db/pm_db/CMakeLists.txt;0;")
add_test(fast_fair_btree_test "/home/qifei/pm_source/ye_db/pm_db/cmake-build/fast_fair_btree_test")
set_tests_properties(fast_fair_btree_test PROPERTIES  _BACKTRACE_TRIPLES "/home/qifei/pm_source/ye_db/pm_db/CMakeLists.txt;344;add_test;/home/qifei/pm_source/ye_db/pm_db/CMakeLists.txt;386;leveldb_test;/home/qifei/pm_source/ye_db/pm_db/CMakeLists.txt;0;")
add_test(env_posix_test "/home/qifei/pm_source/ye_db/pm_db/cmake-build/env_posix_test")
set_tests_properties(env_posix_test PROPERTIES  _BACKTRACE_TRIPLES "/home/qifei/pm_source/ye_db/pm_db/CMakeLists.txt;344;add_test;/home/qifei/pm_source/ye_db/pm_db/CMakeLists.txt;393;leveldb_test;/home/qifei/pm_source/ye_db/pm_db/CMakeLists.txt;0;")
subdirs("third_party/googletest")
subdirs("third_party/benchmark")
